config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  resources :locations
  root 'frontpages#index'
  resources :places
  resources :plans
  resources :frontpages
  get 'onepage/index'
  get '/plans/:plan_id/places' => 'places#index', as: 'plans_places'
  get '/plans/:plan_id/places/new' => 'places#new', as: 'new_plan_place'
  post '/plans/:plan_id/places' => 'places#create'
  get '/plans/:plan_id/places/:id' => 'places#show'
  delete '/plans/:plan_id/places/:id' => 'places#destroy', as:'plan_place_delete'
  # get '/ajax/something' => 'places#getAllPlaces'
  # post '/ajax/something/:id' => 'places#getOnePlace'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/plan.rb
class Plan < ApplicationRecord
  has_many :place
  belongs_to :user
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
  before_action :authenticate_user!
  before_action :set_plan, only: [:show, :edit, :update, :destroy]

  # GET /plans
  # GET /plans.json
  def index
    @plan_show = Plan.all.where(:user_id =>[current_user.id])
    @user = User.all
    @plan_user_id = current_user.id
    @plan = Plan.new
  end

  # GET /plans/1
  # GET /plans/1.json
  def show
    # @places = Places.all
    @plan = Plan.find(params[:id])
  end

  # GET /plans/new
  def new
    @plan = Plan.new

  end

  # GET /plans/1/edit
  def edit
  end

  # POST /plans
  # POST /plans.json
  def create
    @plan = Plan.new(plan_params)
    @plan.user_id = current_user.id
    respond_to do |format|
      if @plan.save
        format.html { redirect_to @plan, notice: 'Plan was successfully created.' }
        format.json { render :show, status: :created, location: @plan }
      else
        format.html { render :new }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plans/1
  # PATCH/PUT /plans/1.json
  def update
    respond_to do |format|
      if @plan.update(plan_params)
        format.html { redirect_to @plan, notice: 'Plan was successfully updated.' }
        format.json { render :show, status: :ok, location: @plan }
      else
        format.html { render :edit }
        format.json { render json: @plan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plans/1
  # DELETE /plans/1.json
  def destroy
    @plan.destroy
    respond_to do |format|
      format.html { redirect_to plans_url, notice: 'Plan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plan
      @plan = Plan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plan_params
     params.require(:plan).permit(:itinerary_name)
    end
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/plans/_form.html.erb
<%= form_with(model: plan, local: true) do |form| %>
  <% if plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plan.errors.count, "error") %> prohibited this plan from being saved:</h2>

      <ul>
        <% plan.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/plans/edit.html.erb
<h1>Editing Plan</h1>

<%= render 'form', plan: @plan %>

<%= link_to 'Show', @plan %> |
<%= link_to 'Back', plans_path %>

app/views/plans/index.html.erb
  <div class="container-fluid ">
    <div class="col-12 d-flex justify-content-center">
      <div class="jumbotron" id="jumbo-2">
        <div class ="row">
          <div class =" col-12 d-flex align-items-start" style="margin-top: 150px;">
            <div class ='offset-1 col-5 d-flex flex-column'>
              <h1 class="display-5">FlyByNight</h1>

              <p class="lead">Got a last minute plan u wanna create?</p>

              </div>
             <div class='offset-2' style="margin-top: -20px">
               <%= form_with scope: :plan, url: plans_path, local: true do |form| %>

                   <div class="row mt-4 d-flex ">

                     <div class ="plan-bar justify-content-start">
                        <div class='row'>
                          <h4 style="color:#ffeecc; padding-left:11px;">Name your trip</h4>
                          </div>
                         <h5><%= form.text_field :itinerary_name %></h5> &ensp;

                        <%= form.submit 'Start planning', :class => 'btn btn-primary start-btn'%>
                     <% end %>
                   </div>
                 </div>
               </div>
          <hr class="my-4"/>
            </div>
          </div>
        </div>

      </div>


  <div class="row" style="margin-left:150px;">
    <table>
      <thead>
        <tr>
          <th colspan="3">Trips</th>
        </tr>
      </thead>

      <tbody>
          <% @plan_show.each do |plan| %>
          <tr>
            <td><h6> <%=plan.itinerary_name%></h6></td>
            <td><h6><%= button_to 'See trip', plan, {method:'get' ,class:'btn btn-primary trip-btn2'} %></h6></td>
            <td><h6><%= button_to 'Delete', plan, method: :delete, class:'btn btn-primary delete-btn', data: { confirm: 'Are you sure?' } %></h6></td>
          </tr>

        <% end %>


      </tbody>
    </table>
    </div>

</div>

app/views/plans/new.html.erb
<%= form_with scope: :plan, url: plans_path, local: true do |form| %>
  <div class="container">
    <h1>New Plan</h1>
    <div class="row">
      <div class ="offset-4 col-4 ">
        <p>Plan Name </p>
          <%= form.text_field :itinerary_name %>

    <%= form.submit %>
      <% end %>
<%= link_to 'Back', plans_path %>
    </div>
  </div>
</div>

app/views/plans/show.html.erb
<div class="container-fluid">
      <div class = "col-12 d-flex flex-row justify-content-center">
        <div class = "row">
          <div class="col-12 d-flex flex-column">
            <h4 >Trip : <%= @plan.itinerary_name%></h4>
            <br />

              <h4 style="color:#a3f7bf;" id="notice"><%= notice %></h4>
            <br />
            <br />
            </div>

          </div>
      </div>
      <div class = "col-12 d-flex justify-content-center">
        <div class="row">

              <%= button_to 'Get some inspiration', locations_path,{method:'get', class:'btn btn-primary trip-btn2'}%> &ensp; &ensp;
              <%= button_to 'Add Place', new_plan_place_path(@plan.id),{method:'get', class:'btn btn-primary trip-btn2'} %> &ensp; &ensp;
              <%= button_to 'View Plan', plans_places_path(@plan.id),{method:'get', class:'btn btn-primary trip-btn2'} %>

            </div>

        </div>


    </div>