config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  resources :locations
  root 'frontpages#index'
  resources :places
  resources :plans
  resources :frontpages
  get 'onepage/index'
  get '/plans/:plan_id/places' => 'places#index', as: 'plans_places'
  get '/plans/:plan_id/places/new' => 'places#new', as: 'new_plan_place'
  post '/plans/:plan_id/places' => 'places#create'
  get '/plans/:plan_id/places/:id' => 'places#show'
  delete '/plans/:plan_id/places/:id' => 'places#destroy', as:'plan_place_delete'
  # get '/ajax/something' => 'places#getAllPlaces'
  # post '/ajax/something/:id' => 'places#getOnePlace'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/location.rb
class Location < ApplicationRecord
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  # GET /locations.json
  def index
    @locations = Location.all
  end

  # GET /locations/1
  # GET /locations/1.json
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  # POST /locations.json
  def create
    @location = Location.new(location_params)

    respond_to do |format|
      if @location.save
        format.html { redirect_to locations_path, notice: 'Location was successfully created.' }
        format.json { render :show, status: :created, location: @location }
      else
        format.html { render :new }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /locations/1
  # PATCH/PUT /locations/1.json
  def update
    respond_to do |format|
      if @location.update(location_params)
        format.html { redirect_to @location, notice: 'Location was successfully updated.' }
        format.json { render :show, status: :ok, location: @location }
      else
        format.html { render :edit }
        format.json { render json: @location.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.json
  def destroy
    @location.destroy
    respond_to do |format|
      format.html { redirect_to locations_url, notice: 'Location was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_location
      @location = Location.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def location_params
        params.require(:location).permit(:country, :location_name, :img_url,:description)
    end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_with(model: location, local: true) do |form| %>
  <% if location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
        <% location.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing Location</h1>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<p id="notice"><%= notice %></p>



<div class='container-fluid'>
  <div class="col-12 d-flex-wrap no-gutters">
    <h1>Locations</h1>
    <% @locations.each_slice(3) do |location| %><br>
      <div class="row">
        <% location.each do |local| %>
          <div class='col-md-4 card-deck'>
            <div class="card">
                <img class="local-img" src='<%=local.img_url%>'/>

              <div class="overlay">
                <div class="card-title" style="padding-left:20px; padding-top:10px;"><strong><h5><%= local.country%></h5></strong></div>
                <hr />
                <div class ="card-title" style="padding-left:20px;"><h5><%= local.location_name%></h5></div>
                <div class="card-text" style="padding-left:20px; padding-right:20px;"><p>
                  <%=local.description%>
                  </p></div>
                <br />
                <div class="d-flex justify-content-center">
                <%= button_to '    Lets Go    ', plans_path, {method: 'get', class:'btn btn-priamry start-btn'} %>
                  </div>


              </div>
            <br />
            </div>
          </div>
        <%end%>
      </div>
    <%end%>
    <br />
    <%= button_to 'Add Recommendation', new_location_path, {method: 'get', class:'btn btn-priamry start-btn'} %>
</div>

</div>




<br>

app/views/locations/new.html.erb
<h1>New Location</h1>



<%= form_with scope: :location, url: locations_path, local: true do |form| %>
  <div class="container">

    <div class="row">
        <div class ="offset-4 col-6 ">
          <h3>New Place</h3>
          <p><%= form.label :Country %>  </p>
            <%= form.text_field :country ,{:required => true}%>
            <br  />
            <br  />
          <p><%= form.label :Location_name %> </p>
            <%= form.text_field :location_name ,{:required => true}%>
            <br  />
            <br  />
            <p><%= form.label :Image_url %> </p>
              <%= form.text_field :img_url %>
          <br/>
          <p><%= form.label :Description%></p>
            <%= form.text_area :description,{rows:'10' , cols:'40'} %>
          <br/>
            <%= form.submit %>
            <% end %>
          </div>

      </div>
      <div class ="row">
        <div class=" offset-4 col-12">
          <br />
              <%= button_to 'Back', locations_path,{method: 'get',class:'btn btn-primary'} %>
          </div>
        </div>


    </div>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>