config/routes.rb
Rails.application.routes.draw do


  devise_for :users
  resources :locations
  root 'frontpages#index'
  resources :places
  resources :plans
  resources :frontpages
  get 'onepage/index'
  get '/plans/:plan_id/places' => 'places#index', as: 'plans_places'
  get '/plans/:plan_id/places/new' => 'places#new', as: 'new_plan_place'
  post '/plans/:plan_id/places' => 'places#create'
  get '/plans/:plan_id/places/:id' => 'places#show'
  delete '/plans/:plan_id/places/:id' => 'places#destroy', as:'plan_place_delete'
  # get '/ajax/something' => 'places#getAllPlaces'
  # post '/ajax/something/:id' => 'places#getOnePlace'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :plan
  has_one :user
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    p "//////////////////////////////"
    p params[:id]
    @place_show = Place.where(:plan_id => params[:plan_id],:user_id => current_user.id  )
    @filteredplace=Place.all

  end

  # GET /places/1
  # GET /places/1.json
  def show
    @places = Place.all
  end

  # GET /places/new
  def new
    @plans = Plan.all
    @locations = Location.all
    # @place = Place.Plan.find(params[:plan_id])
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)
    @place.plan_id = params[:plan_id]
    @place.user_id = current_user.id
    p @place
    p "///////////////"
    respond_to do |format|
      if @place.save

        format.html { redirect_to plans_places_path(plan_id: @place.plan_id, id: @place.id), notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to plans_places_path(:id => (@place.plan_id),id: @place.id), notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # def getAllPlaces
  #   request.body {}
  #   result = Place.new(:place => request.body.newPlace)
  #   result.save
  #   respond_to do |format|
  #     format.json { render json: @place.all }
  #   end
  # end

  # def getOnePlace
  #
  # end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:place_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:country, :name, :start_date, :start_time,:end_time,:session,:notes)
    end
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/places/_form.html.erb
<%= form_with(model: place, local: true) do |form| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
        <% place.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Places</h1>
<div class="container-fluid">
  <div class = "row">
    <div class ="col-9">
      <h4><%= month_calendar events: @place_show do |date, place_show| %></h4>
        <%= date.day %>
        <% place_show.each do |place| %>
          <div>
            <%= place.name %>
             <strong><%=place.start_time.strftime('%H:%M')%></strong>

          </div>
        <% end %>
      <% end %>
      </div>
      <div class="col-3 d-flex flex-column" style=" margin-top:37px;">
        <table style = "border: 1px solid white">
            <tbody style = "border: 1px solid white">
            <% @place_show.each do |place| %>

              <tr style = "border: 1px solid white">
                <td class="notes"> <%=place.name%></td>
                </tr>
                <tr>
                  <td class="notes"> Starts @ <%=place.start_time.strftime('%H:%M')%></td>
                </tr>
                <td class="notes"> <%= place.notes%></td>
                <tr>


                <td class="notes"><%= link_to 'Delete',plan_place_delete_path(:id => (place.plan_id), :place_id =>(place.id)), method: :delete, data: { confirm: 'Are you sure?' } %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <br/>
        <p>   <%= link_to 'Add Place', new_plan_place_path,{method:'get', class:'btn btn-primary trip-btn'} %></p>
        <%= button_to 'Trips', plans_path, {method:'get', class:'btn btn-primary trip-btn'} %>
        <br/>


      </div>
    </div>
  </div>
<div class="row">

</div>


<br>

app/views/places/new.html.erb
<%= form_with scope: :place, url: plans_places_path, local: true do |form| %>
  <div class="container">

    <div class="row">
        <div class ="offset-4 col-6 ">
          <h3>New Place</h3>
          <p><%= form.label :country %>  </p>
            <%= form.text_field :country ,{:required => true}%>
            <br  />
            <br  />
          <p><%= form.label :city_name %> </p>
            <%= form.text_field :name ,{:required => true}%>
            <br  />
            <br  />
          <p><%= form.label :When%></p>
            <%= form.datetime_field :start_time%>
            <br  /><br  />
            <p><%= form.label :Til%></p>
              <%= form.datetime_local_field :end_time%>
          <br/>
          <br/>
          <p><%= form.label :Personal_notes%></p>
            <%= form.text_area :notes,{rows:'10' , cols:'40'}%>
          <br/>
            <%= form.submit 'Add New place', :class => 'btn btn-primary trip-btn2' %>
            <% end %>
          </div>

      </div>
      <div class ="row">
        <div class=" offset-4 col-12">
          <br />
              <%= button_to 'To Calendar', plans_places_path,{method: 'get',class:'btn btn-primary trip-btn2'} %>
          </div>
        </div>


    </div>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_place_path(@place) %> |
      <%= link_to 'Back', plans_path %>